spring.application.name=kishan-suvidha-backend


server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/kisan_suvidha
spring.datasource.username=postgres
spring.datasource.password=yash8252
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

logging.level.root=INFO
logging.level.com.kisansuvidha=DEBUG



jwt.secret=fjkhubfkdbfidgeigghbkfbjdfkbnietgbtejhufdgnejlgheroggirjglfobfbnjhehgehgeuhggfnfnbmjklgjeoihghklgeoge
jwt.expiration=86400000


spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash